-- begin TESTSESSIONVARIABLE_ORDER
alter table TESTSESSIONVARIABLE_ORDER add constraint FK_TESTSESSIONVARIABLE_ORDER_ON_DEPARTMENT foreign key (DEPARTMENT_ID) references TESTSESSIONVARIABLE_DEPARTMENT(ID)^
create index IDX_TESTSESSIONVARIABLE_ORDER_ON_DEPARTMENT on TESTSESSIONVARIABLE_ORDER (DEPARTMENT_ID)^
-- end TESTSESSIONVARIABLE_ORDER
-- begin TESTSESSIONVARIABLE_ORDER_LINE
alter table TESTSESSIONVARIABLE_ORDER_LINE add constraint FK_TESTSESSIONVARIABLE_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references TESTSESSIONVARIABLE_ORDER(ID)^
create index IDX_TESTSESSIONVARIABLE_ORDER_LINE_ON_ORDER on TESTSESSIONVARIABLE_ORDER_LINE (ORDER_ID)^
-- end TESTSESSIONVARIABLE_ORDER_LINE
